; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = blink

[env]
platform = espressif32
board = adafruit_qtpy_esp32s3_n4r2
framework = arduino

build_flags =
  -DARDUINO_USB_MODE=1
  -DARDUINO_USB_CDC_ON_BOOT=1
  -DARDUINO_USB_DFU_ON_BOOT=0
  -std=gnu++17

build_unflags =
  -std=gnu++11

board_build.partitions = default.csv

upload_protocol = esptool
upload_port = /dev/cu.usbmodem*
upload_resetmethod = usb_serial_jtag

monitor_port = /dev/cu.usbmodem*
monitor_speed = 115200
monitor_filters = esp32_exception_decoder

[env:test-stepper]
build_src_filter =
  +<test-stepper/>
lib_deps =
  adafruit/Adafruit NeoPixel

[env:blink]
build_src_filter =
  +<blink/>
lib_deps =
  adafruit/Adafruit NeoPixel

